### PR TITLE
Fixes #942 : Webkit bug for elements in an iframe

### LINKED ISSUE #942: Webkit bug for elements in an iframe
### Expected behavior
When checking the action of an element, it checks if it is an element. When we are in an iframe this verification is falsified during the verification, because it cannot be instantiated with window.Element.

### System configuration
**interact.js version**: 1.10.11
**Browser name and version**: Last version of Safari or Chrome and other webkit browser
**Operating System**: Windows and MacOS

Here is a screenshot to illustrate on a breakpoint:
chrome_L2jfzNnD79

### PR DESCRIPTION
**Pull request by tups**
Make sure to include tests in your pull request.

### CODE REVIEW

File: packages/@interactjs/utils/is.ts [hunk 1]
```diff
@@ -25,8 +25,8 @@ const element = (thing: any): thing is Element => {
   // eslint-disable-next-line import/no-named-as-default-member
   const _window = win.getWindow(thing) || win.window
 
-  return /object|function/.test(typeof _window.Element)
-    ? thing instanceof _window.Element // DOM2
+  return /object|function/.test(typeof HTMLElement)
+    ? (thing instanceof HTMLElement || thing instanceof _window.Element)
     : thing.nodeType === 1 && typeof thing.nodeName === 'string'
 }
```
Comment (taye) [inline packages/@interactjs/utils/is.ts:31]: This should be checking for `Element`, to also include `SVGElement`s. Something like this (I haven't tested it)

```suggestion
  return /object|function/.test(typeof _window.Element)
    ? thing instanceof _window.Element // DOM2
    : /object|function/.test(typeof Element)
      ? (thing instanceof Element || thing instanceof _window.Element)
      : thing.nodeType === 1 && typeof thing.nodeName === 'string'
}
```

**Review by taye — CHANGES_REQUESTED** [review]

File: packages/@interactjs/utils/is.ts (hunk 1 above)
Comment (tups) [reply packages/@interactjs/utils/is.ts]: I tried your solution unfortunately it doesn't work with the bug I saw.

But I completely agree for the Element object, it makes sense :)

I did several tests, and I changed my commit.

**Comment by taye** [comment]
Thank you!
